#!/usr/bin/env python3
"""Generate the bounded lowering policy module from its TOML specification."""
from __future__ import annotations
import argparse
import pathlib
import tomllib


def generate(spec_path: pathlib.Path) -> str:
    with spec_path.open("rb") as stream:
        policy = tomllib.load(stream)["bounded_integer_program"]
    required = {"declaration_count", "variable_count", "instruction_count", "first_opcode",
                "last_opcode", "result_kind", "result_type", "source_rule",
                "initializer_minimum", "initializer_maximum", "addend_minimum", "addend_maximum",
                "subtrahend_minimum", "subtrahend_maximum"}
    if set(policy) != required:
        raise ValueError("bounded_integer_program fields do not match the policy schema")
    if policy["declaration_count"] != 1 or policy["variable_count"] != 1:
        raise ValueError("bounded integer program policy must contain one declaration and variable")
    if policy["instruction_count"] != 2:
        raise ValueError("bounded integer program policy must contain two instructions")
    if policy["initializer_minimum"] >= policy["initializer_maximum"]:
        raise ValueError("initializer policy range must be increasing")
    if policy["addend_minimum"] >= policy["addend_maximum"]:
        raise ValueError("addend policy range must be increasing")
    if policy["subtrahend_minimum"] >= policy["subtrahend_maximum"]:
        raise ValueError("subtrahend policy range must be increasing")
    return "\n".join([
        "! Generated by tools/generate_lowering_policy.py; do not edit.",
        "module ffc_lowering_policy",
        "    use, intrinsic :: iso_fortran_env, only: int32, int64",
        "    use ffc_mir_metadata, only: opcode_add, opcode_return, value_kind_integer",
        "    implicit none",
        "    private",
        "",
        "    integer(int64), parameter, public :: bounded_integer_declaration_count = &",
        f"        {policy['declaration_count']}_int64",
        "    integer(int64), parameter, public :: bounded_integer_variable_count = &",
        f"        {policy['variable_count']}_int64",
        "    integer(int32), parameter, public :: bounded_integer_instruction_count = &",
        f"        {policy['instruction_count']}_int32",
        f"    integer(int32), parameter, public :: bounded_integer_first_opcode = opcode_{policy['first_opcode']}",
        f"    integer(int32), parameter, public :: bounded_integer_last_opcode = opcode_{policy['last_opcode']}",
        f"    integer(int32), parameter, public :: bounded_integer_result_kind = value_kind_{policy['result_kind']}",
        f"    character(len={len(policy['result_type'])}), parameter, public :: &",
        f"        bounded_integer_result_type = '{policy['result_type']}'",
        f"    character(len={len(policy['source_rule'])}), parameter, public :: &",
        f"        bounded_integer_source_rule = '{policy['source_rule']}'",
        f"    integer(int32), parameter, public :: bounded_integer_initializer_minimum = &",
        f"        {policy['initializer_minimum']}_int32",
        f"    integer(int32), parameter, public :: bounded_integer_initializer_maximum = &",
        f"        {policy['initializer_maximum']}_int32",
        "    integer(int32), parameter, public :: bounded_integer_addend_minimum = &",
        f"        {policy['addend_minimum']}_int32",
        "    integer(int32), parameter, public :: bounded_integer_addend_maximum = &",
        f"        {policy['addend_maximum']}_int32",
        "    integer(int32), parameter, public :: bounded_integer_subtrahend_minimum = &",
        f"        {policy['subtrahend_minimum']}_int32",
        "    integer(int32), parameter, public :: bounded_integer_subtrahend_maximum = &",
        f"        {policy['subtrahend_maximum']}_int32",
        "",
        "    public :: bounded_integer_opcode_at",
        "",
        "contains",
        "",
        "    integer(int32) function bounded_integer_opcode_at(index)",
        "        integer(int32), intent(in) :: index",
        "",
        "        select case (index)",
        "        case (0_int32); bounded_integer_opcode_at = bounded_integer_first_opcode",
        "        case (1_int32); bounded_integer_opcode_at = bounded_integer_last_opcode",
        "        case default; bounded_integer_opcode_at = 0_int32",
        "        end select",
        "    end function bounded_integer_opcode_at",
        "",
        "end module ffc_lowering_policy",
        "",
    ])


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--spec", type=pathlib.Path, default=pathlib.Path("spec/lowering_policy.toml"))
    parser.add_argument("--output", type=pathlib.Path, required=True)
    args = parser.parse_args()
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(generate(args.spec), encoding="utf-8")


if __name__ == "__main__":
    main()
