#!/usr/bin/env python3
"""Generate the Fortran mir-v0 metadata module from its TOML specification."""

from __future__ import annotations

import argparse
import pathlib
import tomllib


def read_entries(data: dict, key: str) -> list[dict[str, int | str]]:
    entries = data.get(key, [])
    values = [entry["value"] for entry in entries]
    if values != list(range(1, len(values) + 1)):
        raise ValueError(f"{key} values must be contiguous starting at one")
    if len({entry["name"] for entry in entries}) != len(entries):
        raise ValueError(f"{key} names must be unique")
    return entries


def generate(spec_path: pathlib.Path) -> str:
    with spec_path.open("rb") as stream:
        data = tomllib.load(stream)
    kinds = read_entries(data, "value_kinds")
    opcodes = read_entries(data, "opcodes")
    type_specs = data.get("type_specs", [])
    kind_names = {entry["name"] for entry in kinds}
    type_spec_names = {entry["name"] for entry in type_specs}
    if len(type_spec_names) != len(type_specs):
        raise ValueError("type_specs names must be unique")
    for entry in type_specs:
        if entry["kind"] not in kind_names:
            raise ValueError(f"unknown type-spec kind: {entry['kind']}")
    lines = [
        "! Generated by tools/generate_mir_metadata.py; do not edit.",
        "module ffc_mir_metadata",
        "    use, intrinsic :: iso_fortran_env, only: int32",
        "    implicit none",
        "    private",
        "",
    ]
    for group, entries in (("value_kind", kinds), ("opcode", opcodes)):
        for entry in entries:
            lines.append(
                f"    integer(int32), parameter, public :: {group}_{entry['name']} = "
                f"{entry['value']}_int32"
            )
        lines.append("")
    lines += [
        "    integer(int32), parameter, public :: mir_opcode_histogram_size = &",
        "        opcode_return - opcode_add + 1_int32",
        "",
        "    public :: mir_opcode_name, mir_opcode_value",
        "    public :: mir_value_kind_name, mir_value_kind_value",
        "    public :: mir_type_spec_value_kind, mir_type_spec_name",
        "",
        "contains",
        "",
        "    character(len=32) function mir_opcode_name(opcode)",
        "        integer(int32), intent(in) :: opcode",
        "",
        "        select case (opcode)",
    ]
    for entry in opcodes:
        lines.append(
            f"        case (opcode_{entry['name']}); mir_opcode_name = '{entry['name']}'"
        )
    lines += [
        "        case default; mir_opcode_name = ''",
        "        end select",
        "    end function mir_opcode_name",
        "",
        "    integer(int32) function mir_opcode_value(name)",
        "        character(len=*), intent(in) :: name",
        "",
        "        select case (trim(name))",
    ]
    for entry in opcodes:
        lines.append(
            f"        case ('{entry['name']}'); mir_opcode_value = opcode_{entry['name']}"
        )
    lines += [
        "        case default; mir_opcode_value = 0_int32",
        "        end select",
        "    end function mir_opcode_value",
        "",
        "    character(len=32) function mir_value_kind_name(kind)",
        "        integer(int32), intent(in) :: kind",
        "",
        "        select case (kind)",
    ]
    for entry in kinds:
        lines.append(
            f"        case (value_kind_{entry['name']}); mir_value_kind_name = '{entry['name']}'"
        )
    lines += [
        "        case default; mir_value_kind_name = ''",
        "        end select",
        "    end function mir_value_kind_name",
        "",
        "    integer(int32) function mir_value_kind_value(name)",
        "        character(len=*), intent(in) :: name",
        "",
        "        select case (trim(name))",
    ]
    for entry in kinds:
        lines.append(
            f"        case ('{entry['name']}'); mir_value_kind_value = value_kind_{entry['name']}"
        )
    lines += [
        "        case default; mir_value_kind_value = 0_int32",
        "        end select",
        "    end function mir_value_kind_value",
        "",
        "    integer(int32) function mir_type_spec_value_kind(type_spec)",
        "        character(len=*), intent(in) :: type_spec",
        "",
        "        select case (trim(type_spec))",
    ]
    for entry in type_specs:
        lines.append(
            f"        case ('{entry['name']}'); mir_type_spec_value_kind = "
            f"value_kind_{entry['kind']}"
        )
    lines += [
        "        case default; mir_type_spec_value_kind = 0_int32",
        "        end select",
        "    end function mir_type_spec_value_kind",
        "",
        "    character(len=32) function mir_type_spec_name(type_spec)",
        "        character(len=*), intent(in) :: type_spec",
        "",
        "        select case (trim(type_spec))",
    ]
    for entry in type_specs:
        lines.append(
            f"        case ('{entry['name']}'); mir_type_spec_name = '{entry['type_name']}'"
        )
    lines += [
        "        case default; mir_type_spec_name = ''",
        "        end select",
        "    end function mir_type_spec_name",
        "",
        "end module ffc_mir_metadata",
        "",
    ]
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--spec", type=pathlib.Path, default=pathlib.Path("spec/mir_metadata.toml"))
    parser.add_argument("--output", type=pathlib.Path, required=True)
    args = parser.parse_args()
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(generate(args.spec), encoding="utf-8")


if __name__ == "__main__":
    main()
