! Generated by tools/generate_mir_metadata.py; do not edit.
module ffc_mir_metadata
    use, intrinsic :: iso_fortran_env, only: int32
    implicit none
    private

    integer(int32), parameter, public :: value_kind_integer = 1_int32
    integer(int32), parameter, public :: value_kind_real = 2_int32
    integer(int32), parameter, public :: value_kind_logical = 3_int32
    integer(int32), parameter, public :: value_kind_address = 4_int32
    integer(int32), parameter, public :: value_kind_complex = 5_int32

    integer(int32), parameter, public :: opcode_add = 1_int32
    integer(int32), parameter, public :: opcode_sub = 2_int32
    integer(int32), parameter, public :: opcode_mul = 3_int32
    integer(int32), parameter, public :: opcode_div = 4_int32
    integer(int32), parameter, public :: opcode_load = 5_int32
    integer(int32), parameter, public :: opcode_store = 6_int32
    integer(int32), parameter, public :: opcode_compare = 7_int32
    integer(int32), parameter, public :: opcode_branch = 8_int32
    integer(int32), parameter, public :: opcode_call = 9_int32
    integer(int32), parameter, public :: opcode_return = 10_int32

    character(len=12), parameter, public :: source_rule_program_root = 'program-root'
    character(len=19), parameter, public :: source_rule_frontend_v0_program = 'frontend-v0/program'
    character(len=23), parameter, public :: source_rule_frontend_ast_v1_program = 'frontend-ast-v1/program'

    integer(int32), parameter, public :: mir_opcode_histogram_size = &
        opcode_return - opcode_add + 1_int32

    public :: mir_opcode_name, mir_opcode_value
    public :: mir_value_kind_name, mir_value_kind_value
    public :: mir_type_spec_value_kind, mir_type_spec_name
    public :: mir_source_rule_name, mir_source_rule_value

contains

    character(len=32) function mir_opcode_name(opcode)
        integer(int32), intent(in) :: opcode

        select case (opcode)
        case (opcode_add); mir_opcode_name = 'add'
        case (opcode_sub); mir_opcode_name = 'sub'
        case (opcode_mul); mir_opcode_name = 'mul'
        case (opcode_div); mir_opcode_name = 'div'
        case (opcode_load); mir_opcode_name = 'load'
        case (opcode_store); mir_opcode_name = 'store'
        case (opcode_compare); mir_opcode_name = 'compare'
        case (opcode_branch); mir_opcode_name = 'branch'
        case (opcode_call); mir_opcode_name = 'call'
        case (opcode_return); mir_opcode_name = 'return'
        case default; mir_opcode_name = ''
        end select
    end function mir_opcode_name

    integer(int32) function mir_opcode_value(name)
        character(len=*), intent(in) :: name

        select case (trim(name))
        case ('add'); mir_opcode_value = opcode_add
        case ('sub'); mir_opcode_value = opcode_sub
        case ('mul'); mir_opcode_value = opcode_mul
        case ('div'); mir_opcode_value = opcode_div
        case ('load'); mir_opcode_value = opcode_load
        case ('store'); mir_opcode_value = opcode_store
        case ('compare'); mir_opcode_value = opcode_compare
        case ('branch'); mir_opcode_value = opcode_branch
        case ('call'); mir_opcode_value = opcode_call
        case ('return'); mir_opcode_value = opcode_return
        case default; mir_opcode_value = 0_int32
        end select
    end function mir_opcode_value

    character(len=32) function mir_value_kind_name(kind)
        integer(int32), intent(in) :: kind

        select case (kind)
        case (value_kind_integer); mir_value_kind_name = 'integer'
        case (value_kind_real); mir_value_kind_name = 'real'
        case (value_kind_logical); mir_value_kind_name = 'logical'
        case (value_kind_address); mir_value_kind_name = 'address'
        case (value_kind_complex); mir_value_kind_name = 'complex'
        case default; mir_value_kind_name = ''
        end select
    end function mir_value_kind_name

    integer(int32) function mir_value_kind_value(name)
        character(len=*), intent(in) :: name

        select case (trim(name))
        case ('integer'); mir_value_kind_value = value_kind_integer
        case ('real'); mir_value_kind_value = value_kind_real
        case ('logical'); mir_value_kind_value = value_kind_logical
        case ('address'); mir_value_kind_value = value_kind_address
        case ('complex'); mir_value_kind_value = value_kind_complex
        case default; mir_value_kind_value = 0_int32
        end select
    end function mir_value_kind_value

    integer(int32) function mir_type_spec_value_kind(type_spec)
        character(len=*), intent(in) :: type_spec

        select case (trim(type_spec))
        case ('integer'); mir_type_spec_value_kind = value_kind_integer
        case ('real'); mir_type_spec_value_kind = value_kind_real
        case ('double-precision'); mir_type_spec_value_kind = value_kind_real
        case ('complex'); mir_type_spec_value_kind = value_kind_complex
        case default; mir_type_spec_value_kind = 0_int32
        end select
    end function mir_type_spec_value_kind

    character(len=32) function mir_type_spec_name(type_spec)
        character(len=*), intent(in) :: type_spec

        select case (trim(type_spec))
        case ('integer'); mir_type_spec_name = 'i32'
        case ('real'); mir_type_spec_name = 'f32'
        case ('double-precision'); mir_type_spec_name = 'f64'
        case ('complex'); mir_type_spec_name = 'c32'
        case default; mir_type_spec_name = ''
        end select
    end function mir_type_spec_name

    character(len=64) function mir_source_rule_name(source_rule)
        character(len=*), intent(in) :: source_rule

        select case (trim(source_rule))
        case (source_rule_program_root); mir_source_rule_name = 'program_root'
        case (source_rule_frontend_v0_program); mir_source_rule_name = 'frontend_v0_program'
        case (source_rule_frontend_ast_v1_program); mir_source_rule_name = 'frontend_ast_v1_program'
        case default; mir_source_rule_name = ''
        end select
    end function mir_source_rule_name

    character(len=64) function mir_source_rule_value(name)
        character(len=*), intent(in) :: name

        select case (trim(name))
        case ('program_root'); mir_source_rule_value = source_rule_program_root
        case ('frontend_v0_program'); mir_source_rule_value = source_rule_frontend_v0_program
        case ('frontend_ast_v1_program'); mir_source_rule_value = source_rule_frontend_ast_v1_program
        case default; mir_source_rule_value = ''
        end select
    end function mir_source_rule_value

end module ffc_mir_metadata
