! Generated by tools/generate_lowering_policy.py; do not edit.
module ffc_lowering_policy
    use, intrinsic :: iso_fortran_env, only: int32, int64
    use ffc_mir_metadata, only: opcode_add, opcode_return, value_kind_integer
    implicit none
    private

    integer(int64), parameter, public :: bounded_integer_declaration_count = &
        1_int64
    integer(int64), parameter, public :: bounded_integer_variable_count = &
        1_int64
    integer(int32), parameter, public :: bounded_integer_instruction_count = &
        2_int32
    integer(int32), parameter, public :: bounded_integer_first_opcode = opcode_add
    integer(int32), parameter, public :: bounded_integer_last_opcode = opcode_return
    integer(int32), parameter, public :: bounded_integer_result_kind = value_kind_integer
    character(len=3), parameter, public :: &
        bounded_integer_result_type = 'i32'
    character(len=23), parameter, public :: &
        bounded_integer_source_rule = 'frontend-ast-v1/program'

    public :: bounded_integer_opcode_at

contains

    integer(int32) function bounded_integer_opcode_at(index)
        integer(int32), intent(in) :: index

        select case (index)
        case (0_int32); bounded_integer_opcode_at = bounded_integer_first_opcode
        case (1_int32); bounded_integer_opcode_at = bounded_integer_last_opcode
        case default; bounded_integer_opcode_at = 0_int32
        end select
    end function bounded_integer_opcode_at

end module ffc_lowering_policy
