! Generated by tools/generate_mir_metadata.py; do not edit.
module ffc_mir_metadata
    use, intrinsic :: iso_fortran_env, only: int32
    implicit none
    private

    integer(int32), parameter, public :: value_kind_integer = 1_int32
    integer(int32), parameter, public :: value_kind_real = 2_int32
    integer(int32), parameter, public :: value_kind_logical = 3_int32
    integer(int32), parameter, public :: value_kind_address = 4_int32

    integer(int32), parameter, public :: opcode_add = 1_int32
    integer(int32), parameter, public :: opcode_sub = 2_int32
    integer(int32), parameter, public :: opcode_mul = 3_int32
    integer(int32), parameter, public :: opcode_div = 4_int32
    integer(int32), parameter, public :: opcode_load = 5_int32
    integer(int32), parameter, public :: opcode_store = 6_int32
    integer(int32), parameter, public :: opcode_compare = 7_int32
    integer(int32), parameter, public :: opcode_branch = 8_int32
    integer(int32), parameter, public :: opcode_call = 9_int32
    integer(int32), parameter, public :: opcode_return = 10_int32

    integer(int32), parameter, public :: mir_opcode_histogram_size = &
        opcode_return - opcode_add + 1_int32

    public :: mir_opcode_name, mir_opcode_value
    public :: mir_value_kind_name, mir_value_kind_value

contains

    character(len=32) function mir_opcode_name(opcode)
        integer(int32), intent(in) :: opcode

        select case (opcode)
        case (opcode_add); mir_opcode_name = 'add'
        case (opcode_sub); mir_opcode_name = 'sub'
        case (opcode_mul); mir_opcode_name = 'mul'
        case (opcode_div); mir_opcode_name = 'div'
        case (opcode_load); mir_opcode_name = 'load'
        case (opcode_store); mir_opcode_name = 'store'
        case (opcode_compare); mir_opcode_name = 'compare'
        case (opcode_branch); mir_opcode_name = 'branch'
        case (opcode_call); mir_opcode_name = 'call'
        case (opcode_return); mir_opcode_name = 'return'
        case default; mir_opcode_name = ''
        end select
    end function mir_opcode_name

    integer(int32) function mir_opcode_value(name)
        character(len=*), intent(in) :: name

        select case (trim(name))
        case ('add'); mir_opcode_value = opcode_add
        case ('sub'); mir_opcode_value = opcode_sub
        case ('mul'); mir_opcode_value = opcode_mul
        case ('div'); mir_opcode_value = opcode_div
        case ('load'); mir_opcode_value = opcode_load
        case ('store'); mir_opcode_value = opcode_store
        case ('compare'); mir_opcode_value = opcode_compare
        case ('branch'); mir_opcode_value = opcode_branch
        case ('call'); mir_opcode_value = opcode_call
        case ('return'); mir_opcode_value = opcode_return
        case default; mir_opcode_value = 0_int32
        end select
    end function mir_opcode_value

    character(len=32) function mir_value_kind_name(kind)
        integer(int32), intent(in) :: kind

        select case (kind)
        case (value_kind_integer); mir_value_kind_name = 'integer'
        case (value_kind_real); mir_value_kind_name = 'real'
        case (value_kind_logical); mir_value_kind_name = 'logical'
        case (value_kind_address); mir_value_kind_name = 'address'
        case default; mir_value_kind_name = ''
        end select
    end function mir_value_kind_name

    integer(int32) function mir_value_kind_value(name)
        character(len=*), intent(in) :: name

        select case (trim(name))
        case ('integer'); mir_value_kind_value = value_kind_integer
        case ('real'); mir_value_kind_value = value_kind_real
        case ('logical'); mir_value_kind_value = value_kind_logical
        case ('address'); mir_value_kind_value = value_kind_address
        case default; mir_value_kind_value = 0_int32
        end select
    end function mir_value_kind_value

end module ffc_mir_metadata
