! Generated by tools/generate_mir_metadata.py; do not edit.
module ffc_mir_metadata
    use, intrinsic :: iso_fortran_env, only: int32
    implicit none
    private

    integer(int32), parameter, public :: value_kind_integer = 1_int32
    integer(int32), parameter, public :: value_kind_real = 2_int32
    integer(int32), parameter, public :: value_kind_logical = 3_int32
    integer(int32), parameter, public :: value_kind_address = 4_int32
    integer(int32), parameter, public :: value_kind_complex = 5_int32
    integer(int32), parameter, public :: value_kind_character = 6_int32

    integer(int32), parameter, public :: opcode_add = 1_int32
    integer(int32), parameter, public :: opcode_sub = 2_int32
    integer(int32), parameter, public :: opcode_mul = 3_int32
    integer(int32), parameter, public :: opcode_div = 4_int32
    integer(int32), parameter, public :: opcode_load = 5_int32
    integer(int32), parameter, public :: opcode_store = 6_int32
    integer(int32), parameter, public :: opcode_compare = 7_int32
    integer(int32), parameter, public :: opcode_branch = 8_int32
    integer(int32), parameter, public :: opcode_call = 9_int32
    integer(int32), parameter, public :: opcode_return = 10_int32
    integer(int32), parameter, public :: opcode_const = 11_int32

    character(len=12), parameter, public :: source_rule_program_root = 'program-root'
    character(len=19), parameter, public :: source_rule_frontend_v0_program = 'frontend-v0/program'
    character(len=23), parameter, public :: source_rule_frontend_ast_v1_program = 'frontend-ast-v1/program'
    character(len=26), parameter, public :: source_rule_frontend_ast_v1_assignment = 'frontend-ast-v1/assignment'
    character(len=26), parameter, public :: source_rule_frontend_ast_v1_expression = 'frontend-ast-v1/expression'
    character(len=32), parameter, public :: source_rule_frontend_ast_v1_storage_sequence = 'frontend-ast-v1/storage-sequence'
    character(len=34), parameter, public :: source_rule_frontend_ast_v1_storage_sequence_3 = 'frontend-ast-v1/storage-sequence-3'
    character(len=34), parameter, public :: source_rule_frontend_ast_v1_storage_sequence_4 = 'frontend-ast-v1/storage-sequence-4'
    character(len=34), parameter, public :: source_rule_frontend_ast_v1_storage_sequence_5 = 'frontend-ast-v1/storage-sequence-5'
    character(len=30), parameter, public :: source_rule_frontend_ast_v2_execution_part = 'frontend-ast-v2/execution-part'

    integer(int32), parameter, public :: instruction_shape_frontend_ast_v1_integer_program_count = 2_int32
    integer(int32), parameter, public :: instruction_shape_frontend_ast_v1_integer_program_opcode_0 = opcode_add
    integer(int32), parameter, public :: instruction_shape_frontend_ast_v1_integer_program_opcode_1 = opcode_return
    integer(int32), parameter, public :: instruction_shape_frontend_ast_v1_integer_program_result_kind = value_kind_integer
    character(len=3), parameter, public :: instruction_shape_frontend_ast_v1_integer_program_result_type = 'i32'
    character(len=23), parameter, public :: instruction_shape_frontend_ast_v1_integer_program_source_rule = 'frontend-ast-v1/program'

    integer(int32), parameter, public :: instruction_shape_frontend_ast_v1_int_assign_count = 2_int32
    integer(int32), parameter, public :: instruction_shape_frontend_ast_v1_int_assign_opcode_0 = opcode_store
    integer(int32), parameter, public :: instruction_shape_frontend_ast_v1_int_assign_opcode_1 = opcode_return
    integer(int32), parameter, public :: instruction_shape_frontend_ast_v1_int_assign_result_kind = value_kind_integer
    character(len=3), parameter, public :: instruction_shape_frontend_ast_v1_int_assign_result_type = 'i32'
    character(len=26), parameter, public :: instruction_shape_frontend_ast_v1_int_assign_source_rule = 'frontend-ast-v1/assignment'

    integer(int32), parameter, public :: instruction_shape_frontend_ast_v1_int_lit_assign_count = 3_int32
    integer(int32), parameter, public :: instruction_shape_frontend_ast_v1_int_lit_assign_opcode_0 = opcode_const
    integer(int32), parameter, public :: instruction_shape_frontend_ast_v1_int_lit_assign_opcode_1 = opcode_store
    integer(int32), parameter, public :: instruction_shape_frontend_ast_v1_int_lit_assign_opcode_2 = opcode_return
    integer(int32), parameter, public :: instruction_shape_frontend_ast_v1_int_lit_assign_result_kind = value_kind_integer
    character(len=3), parameter, public :: instruction_shape_frontend_ast_v1_int_lit_assign_result_type = 'i32'
    character(len=26), parameter, public :: instruction_shape_frontend_ast_v1_int_lit_assign_source_rule = 'frontend-ast-v1/assignment'

    integer(int32), parameter, public :: instruction_shape_frontend_ast_v1_int_expr_assign_count = 5_int32
    integer(int32), parameter, public :: instruction_shape_frontend_ast_v1_int_expr_assign_opcode_0 = opcode_const
    integer(int32), parameter, public :: instruction_shape_frontend_ast_v1_int_expr_assign_opcode_1 = opcode_const
    integer(int32), parameter, public :: instruction_shape_frontend_ast_v1_int_expr_assign_opcode_2 = opcode_add
    integer(int32), parameter, public :: instruction_shape_frontend_ast_v1_int_expr_assign_opcode_3 = opcode_store
    integer(int32), parameter, public :: instruction_shape_frontend_ast_v1_int_expr_assign_opcode_4 = opcode_return
    integer(int32), parameter, public :: instruction_shape_frontend_ast_v1_int_expr_assign_result_kind = value_kind_integer
    character(len=3), parameter, public :: instruction_shape_frontend_ast_v1_int_expr_assign_result_type = 'i32'
    character(len=26), parameter, public :: instruction_shape_frontend_ast_v1_int_expr_assign_source_rule = 'frontend-ast-v1/expression'

    integer(int32), parameter, public :: instruction_shape_frontend_ast_v1_int_var_assign_count = 5_int32
    integer(int32), parameter, public :: instruction_shape_frontend_ast_v1_int_var_assign_opcode_0 = opcode_load
    integer(int32), parameter, public :: instruction_shape_frontend_ast_v1_int_var_assign_opcode_1 = opcode_const
    integer(int32), parameter, public :: instruction_shape_frontend_ast_v1_int_var_assign_opcode_2 = opcode_add
    integer(int32), parameter, public :: instruction_shape_frontend_ast_v1_int_var_assign_opcode_3 = opcode_store
    integer(int32), parameter, public :: instruction_shape_frontend_ast_v1_int_var_assign_opcode_4 = opcode_return
    integer(int32), parameter, public :: instruction_shape_frontend_ast_v1_int_var_assign_result_kind = value_kind_integer
    character(len=3), parameter, public :: instruction_shape_frontend_ast_v1_int_var_assign_result_type = 'i32'
    character(len=26), parameter, public :: instruction_shape_frontend_ast_v1_int_var_assign_source_rule = 'frontend-ast-v1/expression'

    integer(int32), parameter, public :: instruction_shape_frontend_ast_v1_int_mul_assign_count = 5_int32
    integer(int32), parameter, public :: instruction_shape_frontend_ast_v1_int_mul_assign_opcode_0 = opcode_const
    integer(int32), parameter, public :: instruction_shape_frontend_ast_v1_int_mul_assign_opcode_1 = opcode_const
    integer(int32), parameter, public :: instruction_shape_frontend_ast_v1_int_mul_assign_opcode_2 = opcode_mul
    integer(int32), parameter, public :: instruction_shape_frontend_ast_v1_int_mul_assign_opcode_3 = opcode_store
    integer(int32), parameter, public :: instruction_shape_frontend_ast_v1_int_mul_assign_opcode_4 = opcode_return
    integer(int32), parameter, public :: instruction_shape_frontend_ast_v1_int_mul_assign_result_kind = value_kind_integer
    character(len=3), parameter, public :: instruction_shape_frontend_ast_v1_int_mul_assign_result_type = 'i32'
    character(len=26), parameter, public :: instruction_shape_frontend_ast_v1_int_mul_assign_source_rule = 'frontend-ast-v1/expression'

    integer(int32), parameter, public :: instruction_shape_frontend_ast_v1_int_div_assign_count = 5_int32
    integer(int32), parameter, public :: instruction_shape_frontend_ast_v1_int_div_assign_opcode_0 = opcode_const
    integer(int32), parameter, public :: instruction_shape_frontend_ast_v1_int_div_assign_opcode_1 = opcode_const
    integer(int32), parameter, public :: instruction_shape_frontend_ast_v1_int_div_assign_opcode_2 = opcode_div
    integer(int32), parameter, public :: instruction_shape_frontend_ast_v1_int_div_assign_opcode_3 = opcode_store
    integer(int32), parameter, public :: instruction_shape_frontend_ast_v1_int_div_assign_opcode_4 = opcode_return
    integer(int32), parameter, public :: instruction_shape_frontend_ast_v1_int_div_assign_result_kind = value_kind_integer
    character(len=3), parameter, public :: instruction_shape_frontend_ast_v1_int_div_assign_result_type = 'i32'
    character(len=26), parameter, public :: instruction_shape_frontend_ast_v1_int_div_assign_source_rule = 'frontend-ast-v1/expression'

    integer(int32), parameter, public :: instruction_shape_frontend_ast_v1_int_sub_assign_count = 5_int32
    integer(int32), parameter, public :: instruction_shape_frontend_ast_v1_int_sub_assign_opcode_0 = opcode_const
    integer(int32), parameter, public :: instruction_shape_frontend_ast_v1_int_sub_assign_opcode_1 = opcode_const
    integer(int32), parameter, public :: instruction_shape_frontend_ast_v1_int_sub_assign_opcode_2 = opcode_sub
    integer(int32), parameter, public :: instruction_shape_frontend_ast_v1_int_sub_assign_opcode_3 = opcode_store
    integer(int32), parameter, public :: instruction_shape_frontend_ast_v1_int_sub_assign_opcode_4 = opcode_return
    integer(int32), parameter, public :: instruction_shape_frontend_ast_v1_int_sub_assign_result_kind = value_kind_integer
    character(len=3), parameter, public :: instruction_shape_frontend_ast_v1_int_sub_assign_result_type = 'i32'
    character(len=26), parameter, public :: instruction_shape_frontend_ast_v1_int_sub_assign_source_rule = 'frontend-ast-v1/expression'

    integer(int32), parameter, public :: instruction_shape_frontend_ast_v1_int_seq_count = 7_int32
    integer(int32), parameter, public :: instruction_shape_frontend_ast_v1_int_seq_opcode_0 = opcode_const
    integer(int32), parameter, public :: instruction_shape_frontend_ast_v1_int_seq_opcode_1 = opcode_store
    integer(int32), parameter, public :: instruction_shape_frontend_ast_v1_int_seq_opcode_2 = opcode_load
    integer(int32), parameter, public :: instruction_shape_frontend_ast_v1_int_seq_opcode_3 = opcode_const
    integer(int32), parameter, public :: instruction_shape_frontend_ast_v1_int_seq_opcode_4 = opcode_add
    integer(int32), parameter, public :: instruction_shape_frontend_ast_v1_int_seq_opcode_5 = opcode_store
    integer(int32), parameter, public :: instruction_shape_frontend_ast_v1_int_seq_opcode_6 = opcode_return
    integer(int32), parameter, public :: instruction_shape_frontend_ast_v1_int_seq_result_kind = value_kind_integer
    character(len=3), parameter, public :: instruction_shape_frontend_ast_v1_int_seq_result_type = 'i32'
    character(len=32), parameter, public :: instruction_shape_frontend_ast_v1_int_seq_source_rule = 'frontend-ast-v1/storage-sequence'

    integer(int32), parameter, public :: instruction_shape_frontend_ast_v1_int_seq_3_count = 11_int32
    integer(int32), parameter, public :: instruction_shape_frontend_ast_v1_int_seq_3_opcode_0 = opcode_const
    integer(int32), parameter, public :: instruction_shape_frontend_ast_v1_int_seq_3_opcode_1 = opcode_store
    integer(int32), parameter, public :: instruction_shape_frontend_ast_v1_int_seq_3_opcode_2 = opcode_load
    integer(int32), parameter, public :: instruction_shape_frontend_ast_v1_int_seq_3_opcode_3 = opcode_const
    integer(int32), parameter, public :: instruction_shape_frontend_ast_v1_int_seq_3_opcode_4 = opcode_add
    integer(int32), parameter, public :: instruction_shape_frontend_ast_v1_int_seq_3_opcode_5 = opcode_store
    integer(int32), parameter, public :: instruction_shape_frontend_ast_v1_int_seq_3_opcode_6 = opcode_load
    integer(int32), parameter, public :: instruction_shape_frontend_ast_v1_int_seq_3_opcode_7 = opcode_const
    integer(int32), parameter, public :: instruction_shape_frontend_ast_v1_int_seq_3_opcode_8 = opcode_add
    integer(int32), parameter, public :: instruction_shape_frontend_ast_v1_int_seq_3_opcode_9 = opcode_store
    integer(int32), parameter, public :: instruction_shape_frontend_ast_v1_int_seq_3_opcode_10 = opcode_return
    integer(int32), parameter, public :: instruction_shape_frontend_ast_v1_int_seq_3_result_kind = value_kind_integer
    character(len=3), parameter, public :: instruction_shape_frontend_ast_v1_int_seq_3_result_type = 'i32'
    character(len=34), parameter, public :: instruction_shape_frontend_ast_v1_int_seq_3_source_rule = 'frontend-ast-v1/storage-sequence-3'

    integer(int32), parameter, public :: instruction_shape_frontend_ast_v1_int_seq_4_count = 15_int32
    integer(int32), parameter, public :: instruction_shape_frontend_ast_v1_int_seq_4_opcode_0 = opcode_const
    integer(int32), parameter, public :: instruction_shape_frontend_ast_v1_int_seq_4_opcode_1 = opcode_store
    integer(int32), parameter, public :: instruction_shape_frontend_ast_v1_int_seq_4_opcode_2 = opcode_load
    integer(int32), parameter, public :: instruction_shape_frontend_ast_v1_int_seq_4_opcode_3 = opcode_const
    integer(int32), parameter, public :: instruction_shape_frontend_ast_v1_int_seq_4_opcode_4 = opcode_add
    integer(int32), parameter, public :: instruction_shape_frontend_ast_v1_int_seq_4_opcode_5 = opcode_store
    integer(int32), parameter, public :: instruction_shape_frontend_ast_v1_int_seq_4_opcode_6 = opcode_load
    integer(int32), parameter, public :: instruction_shape_frontend_ast_v1_int_seq_4_opcode_7 = opcode_const
    integer(int32), parameter, public :: instruction_shape_frontend_ast_v1_int_seq_4_opcode_8 = opcode_add
    integer(int32), parameter, public :: instruction_shape_frontend_ast_v1_int_seq_4_opcode_9 = opcode_store
    integer(int32), parameter, public :: instruction_shape_frontend_ast_v1_int_seq_4_opcode_10 = opcode_load
    integer(int32), parameter, public :: instruction_shape_frontend_ast_v1_int_seq_4_opcode_11 = opcode_const
    integer(int32), parameter, public :: instruction_shape_frontend_ast_v1_int_seq_4_opcode_12 = opcode_add
    integer(int32), parameter, public :: instruction_shape_frontend_ast_v1_int_seq_4_opcode_13 = opcode_store
    integer(int32), parameter, public :: instruction_shape_frontend_ast_v1_int_seq_4_opcode_14 = opcode_return
    integer(int32), parameter, public :: instruction_shape_frontend_ast_v1_int_seq_4_result_kind = value_kind_integer
    character(len=3), parameter, public :: instruction_shape_frontend_ast_v1_int_seq_4_result_type = 'i32'
    character(len=34), parameter, public :: instruction_shape_frontend_ast_v1_int_seq_4_source_rule = 'frontend-ast-v1/storage-sequence-4'

    integer(int32), parameter, public :: instruction_shape_frontend_ast_v1_int_seq_5_count = 19_int32
    integer(int32), parameter, public :: instruction_shape_frontend_ast_v1_int_seq_5_opcode_0 = opcode_const
    integer(int32), parameter, public :: instruction_shape_frontend_ast_v1_int_seq_5_opcode_1 = opcode_store
    integer(int32), parameter, public :: instruction_shape_frontend_ast_v1_int_seq_5_opcode_2 = opcode_load
    integer(int32), parameter, public :: instruction_shape_frontend_ast_v1_int_seq_5_opcode_3 = opcode_const
    integer(int32), parameter, public :: instruction_shape_frontend_ast_v1_int_seq_5_opcode_4 = opcode_add
    integer(int32), parameter, public :: instruction_shape_frontend_ast_v1_int_seq_5_opcode_5 = opcode_store
    integer(int32), parameter, public :: instruction_shape_frontend_ast_v1_int_seq_5_opcode_6 = opcode_load
    integer(int32), parameter, public :: instruction_shape_frontend_ast_v1_int_seq_5_opcode_7 = opcode_const
    integer(int32), parameter, public :: instruction_shape_frontend_ast_v1_int_seq_5_opcode_8 = opcode_add
    integer(int32), parameter, public :: instruction_shape_frontend_ast_v1_int_seq_5_opcode_9 = opcode_store
    integer(int32), parameter, public :: instruction_shape_frontend_ast_v1_int_seq_5_opcode_10 = opcode_load
    integer(int32), parameter, public :: instruction_shape_frontend_ast_v1_int_seq_5_opcode_11 = opcode_const
    integer(int32), parameter, public :: instruction_shape_frontend_ast_v1_int_seq_5_opcode_12 = opcode_add
    integer(int32), parameter, public :: instruction_shape_frontend_ast_v1_int_seq_5_opcode_13 = opcode_store
    integer(int32), parameter, public :: instruction_shape_frontend_ast_v1_int_seq_5_opcode_14 = opcode_load
    integer(int32), parameter, public :: instruction_shape_frontend_ast_v1_int_seq_5_opcode_15 = opcode_const
    integer(int32), parameter, public :: instruction_shape_frontend_ast_v1_int_seq_5_opcode_16 = opcode_add
    integer(int32), parameter, public :: instruction_shape_frontend_ast_v1_int_seq_5_opcode_17 = opcode_store
    integer(int32), parameter, public :: instruction_shape_frontend_ast_v1_int_seq_5_opcode_18 = opcode_return
    integer(int32), parameter, public :: instruction_shape_frontend_ast_v1_int_seq_5_result_kind = value_kind_integer
    character(len=3), parameter, public :: instruction_shape_frontend_ast_v1_int_seq_5_result_type = 'i32'
    character(len=34), parameter, public :: instruction_shape_frontend_ast_v1_int_seq_5_source_rule = 'frontend-ast-v1/storage-sequence-5'

    integer(int32), parameter, public :: instruction_shape_frontend_ast_v2_int_exec_count = 7_int32
    integer(int32), parameter, public :: instruction_shape_frontend_ast_v2_int_exec_opcode_0 = opcode_const
    integer(int32), parameter, public :: instruction_shape_frontend_ast_v2_int_exec_opcode_1 = opcode_store
    integer(int32), parameter, public :: instruction_shape_frontend_ast_v2_int_exec_opcode_2 = opcode_load
    integer(int32), parameter, public :: instruction_shape_frontend_ast_v2_int_exec_opcode_3 = opcode_const
    integer(int32), parameter, public :: instruction_shape_frontend_ast_v2_int_exec_opcode_4 = opcode_add
    integer(int32), parameter, public :: instruction_shape_frontend_ast_v2_int_exec_opcode_5 = opcode_store
    integer(int32), parameter, public :: instruction_shape_frontend_ast_v2_int_exec_opcode_6 = opcode_return
    integer(int32), parameter, public :: instruction_shape_frontend_ast_v2_int_exec_result_kind = value_kind_integer
    character(len=3), parameter, public :: instruction_shape_frontend_ast_v2_int_exec_result_type = 'i32'
    character(len=30), parameter, public :: instruction_shape_frontend_ast_v2_int_exec_source_rule = 'frontend-ast-v2/execution-part'

    integer(int32), parameter, public :: instruction_shape_frontend_ast_v1_logical_program_count = 2_int32
    integer(int32), parameter, public :: instruction_shape_frontend_ast_v1_logical_program_opcode_0 = opcode_add
    integer(int32), parameter, public :: instruction_shape_frontend_ast_v1_logical_program_opcode_1 = opcode_return
    integer(int32), parameter, public :: instruction_shape_frontend_ast_v1_logical_program_result_kind = value_kind_logical
    character(len=7), parameter, public :: instruction_shape_frontend_ast_v1_logical_program_result_type = 'logical'
    character(len=23), parameter, public :: instruction_shape_frontend_ast_v1_logical_program_source_rule = 'frontend-ast-v1/program'

    integer(int32), parameter, public :: instruction_shape_frontend_ast_v1_real_program_count = 2_int32
    integer(int32), parameter, public :: instruction_shape_frontend_ast_v1_real_program_opcode_0 = opcode_add
    integer(int32), parameter, public :: instruction_shape_frontend_ast_v1_real_program_opcode_1 = opcode_return
    integer(int32), parameter, public :: instruction_shape_frontend_ast_v1_real_program_result_kind = value_kind_real
    character(len=3), parameter, public :: instruction_shape_frontend_ast_v1_real_program_result_type = 'f32'
    character(len=23), parameter, public :: instruction_shape_frontend_ast_v1_real_program_source_rule = 'frontend-ast-v1/program'

    integer(int32), parameter, public :: instruction_shape_frontend_ast_v1_dp_program_count = 2_int32
    integer(int32), parameter, public :: instruction_shape_frontend_ast_v1_dp_program_opcode_0 = opcode_add
    integer(int32), parameter, public :: instruction_shape_frontend_ast_v1_dp_program_opcode_1 = opcode_return
    integer(int32), parameter, public :: instruction_shape_frontend_ast_v1_dp_program_result_kind = value_kind_real
    character(len=3), parameter, public :: instruction_shape_frontend_ast_v1_dp_program_result_type = 'f64'
    character(len=23), parameter, public :: instruction_shape_frontend_ast_v1_dp_program_source_rule = 'frontend-ast-v1/program'

    integer(int32), parameter, public :: instruction_shape_frontend_ast_v1_complex_program_count = 2_int32
    integer(int32), parameter, public :: instruction_shape_frontend_ast_v1_complex_program_opcode_0 = opcode_add
    integer(int32), parameter, public :: instruction_shape_frontend_ast_v1_complex_program_opcode_1 = opcode_return
    integer(int32), parameter, public :: instruction_shape_frontend_ast_v1_complex_program_result_kind = value_kind_complex
    character(len=3), parameter, public :: instruction_shape_frontend_ast_v1_complex_program_result_type = 'c32'
    character(len=23), parameter, public :: instruction_shape_frontend_ast_v1_complex_program_source_rule = 'frontend-ast-v1/program'

    integer(int32), parameter, public :: instruction_shape_frontend_ast_v1_character_program_count = 2_int32
    integer(int32), parameter, public :: instruction_shape_frontend_ast_v1_character_program_opcode_0 = opcode_add
    integer(int32), parameter, public :: instruction_shape_frontend_ast_v1_character_program_opcode_1 = opcode_return
    integer(int32), parameter, public :: instruction_shape_frontend_ast_v1_character_program_result_kind = value_kind_character
    character(len=9), parameter, public :: instruction_shape_frontend_ast_v1_character_program_result_type = 'character'
    character(len=23), parameter, public :: instruction_shape_frontend_ast_v1_character_program_source_rule = 'frontend-ast-v1/program'

    integer(int32), parameter, public :: mir_opcode_histogram_size = &
        11_int32

    public :: mir_opcode_name, mir_opcode_value
    public :: mir_value_kind_name, mir_value_kind_value
    public :: mir_type_spec_value_kind, mir_type_spec_name
    public :: mir_source_rule_name, mir_source_rule_value
    public :: mir_frontend_ast_v1_integer_expression_route
    public :: mir_frontend_ast_v1_integer_expression_instruction_count
    public :: mir_frontend_ast_v1_integer_expression_opcode
    public :: mir_frontend_ast_v1_integer_expression_result_kind
    public :: mir_frontend_ast_v1_integer_expression_result_type
    public :: mir_frontend_ast_v1_integer_expression_source_rule
    public :: mir_frontend_ast_v1_integer_expression_literal_value
    public :: mir_frontend_ast_v1_integer_expression_result_id
    public :: mir_frontend_ast_v1_integer_expression_storage_key

contains

    character(len=32) function mir_opcode_name(opcode)
        integer(int32), intent(in) :: opcode

        select case (opcode)
        case (opcode_add); mir_opcode_name = 'add'
        case (opcode_sub); mir_opcode_name = 'sub'
        case (opcode_mul); mir_opcode_name = 'mul'
        case (opcode_div); mir_opcode_name = 'div'
        case (opcode_load); mir_opcode_name = 'load'
        case (opcode_store); mir_opcode_name = 'store'
        case (opcode_compare); mir_opcode_name = 'compare'
        case (opcode_branch); mir_opcode_name = 'branch'
        case (opcode_call); mir_opcode_name = 'call'
        case (opcode_return); mir_opcode_name = 'return'
        case (opcode_const); mir_opcode_name = 'const'
        case default; mir_opcode_name = ''
        end select
    end function mir_opcode_name

    integer(int32) function mir_opcode_value(name)
        character(len=*), intent(in) :: name

        select case (trim(name))
        case ('add'); mir_opcode_value = opcode_add
        case ('sub'); mir_opcode_value = opcode_sub
        case ('mul'); mir_opcode_value = opcode_mul
        case ('div'); mir_opcode_value = opcode_div
        case ('load'); mir_opcode_value = opcode_load
        case ('store'); mir_opcode_value = opcode_store
        case ('compare'); mir_opcode_value = opcode_compare
        case ('branch'); mir_opcode_value = opcode_branch
        case ('call'); mir_opcode_value = opcode_call
        case ('return'); mir_opcode_value = opcode_return
        case ('const'); mir_opcode_value = opcode_const
        case default; mir_opcode_value = 0_int32
        end select
    end function mir_opcode_value

    character(len=32) function mir_value_kind_name(kind)
        integer(int32), intent(in) :: kind

        select case (kind)
        case (value_kind_integer); mir_value_kind_name = 'integer'
        case (value_kind_real); mir_value_kind_name = 'real'
        case (value_kind_logical); mir_value_kind_name = 'logical'
        case (value_kind_address); mir_value_kind_name = 'address'
        case (value_kind_complex); mir_value_kind_name = 'complex'
        case (value_kind_character); mir_value_kind_name = 'character'
        case default; mir_value_kind_name = ''
        end select
    end function mir_value_kind_name

    integer(int32) function mir_value_kind_value(name)
        character(len=*), intent(in) :: name

        select case (trim(name))
        case ('integer'); mir_value_kind_value = value_kind_integer
        case ('real'); mir_value_kind_value = value_kind_real
        case ('logical'); mir_value_kind_value = value_kind_logical
        case ('address'); mir_value_kind_value = value_kind_address
        case ('complex'); mir_value_kind_value = value_kind_complex
        case ('character'); mir_value_kind_value = value_kind_character
        case default; mir_value_kind_value = 0_int32
        end select
    end function mir_value_kind_value

    integer(int32) function mir_type_spec_value_kind(type_spec)
        character(len=*), intent(in) :: type_spec

        select case (trim(type_spec))
        case ('integer'); mir_type_spec_value_kind = value_kind_integer
        case ('logical'); mir_type_spec_value_kind = value_kind_logical
        case ('real'); mir_type_spec_value_kind = value_kind_real
        case ('double-precision'); mir_type_spec_value_kind = value_kind_real
        case ('complex'); mir_type_spec_value_kind = value_kind_complex
        case ('character'); mir_type_spec_value_kind = value_kind_character
        case default; mir_type_spec_value_kind = 0_int32
        end select
    end function mir_type_spec_value_kind

    character(len=32) function mir_type_spec_name(type_spec)
        character(len=*), intent(in) :: type_spec

        select case (trim(type_spec))
        case ('integer'); mir_type_spec_name = 'i32'
        case ('logical'); mir_type_spec_name = 'logical'
        case ('real'); mir_type_spec_name = 'f32'
        case ('double-precision'); mir_type_spec_name = 'f64'
        case ('complex'); mir_type_spec_name = 'c32'
        case ('character'); mir_type_spec_name = 'character'
        case default; mir_type_spec_name = ''
        end select
    end function mir_type_spec_name

    character(len=64) function mir_source_rule_name(source_rule)
        character(len=*), intent(in) :: source_rule

        select case (trim(source_rule))
        case (source_rule_program_root); mir_source_rule_name = 'program_root'
        case (source_rule_frontend_v0_program); mir_source_rule_name = 'frontend_v0_program'
        case (source_rule_frontend_ast_v1_program); mir_source_rule_name = 'frontend_ast_v1_program'
        case (source_rule_frontend_ast_v1_assignment); mir_source_rule_name = 'frontend_ast_v1_assignment'
        case (source_rule_frontend_ast_v1_expression); mir_source_rule_name = 'frontend_ast_v1_expression'
        case (source_rule_frontend_ast_v1_storage_sequence); mir_source_rule_name = 'frontend_ast_v1_storage_sequence'
        case (source_rule_frontend_ast_v1_storage_sequence_3); mir_source_rule_name = 'frontend_ast_v1_storage_sequence_3'
        case (source_rule_frontend_ast_v1_storage_sequence_4); mir_source_rule_name = 'frontend_ast_v1_storage_sequence_4'
        case (source_rule_frontend_ast_v1_storage_sequence_5); mir_source_rule_name = 'frontend_ast_v1_storage_sequence_5'
        case (source_rule_frontend_ast_v2_execution_part); mir_source_rule_name = 'frontend_ast_v2_execution_part'
        case default; mir_source_rule_name = ''
        end select
    end function mir_source_rule_name

    character(len=64) function mir_source_rule_value(name)
        character(len=*), intent(in) :: name

        select case (trim(name))
        case ('program_root'); mir_source_rule_value = source_rule_program_root
        case ('frontend_v0_program'); mir_source_rule_value = source_rule_frontend_v0_program
        case ('frontend_ast_v1_program'); mir_source_rule_value = source_rule_frontend_ast_v1_program
        case ('frontend_ast_v1_assignment'); mir_source_rule_value = source_rule_frontend_ast_v1_assignment
        case ('frontend_ast_v1_expression'); mir_source_rule_value = source_rule_frontend_ast_v1_expression
        case ('frontend_ast_v1_storage_sequence'); mir_source_rule_value = source_rule_frontend_ast_v1_storage_sequence
        case ('frontend_ast_v1_storage_sequence_3'); mir_source_rule_value = source_rule_frontend_ast_v1_storage_sequence_3
        case ('frontend_ast_v1_storage_sequence_4'); mir_source_rule_value = source_rule_frontend_ast_v1_storage_sequence_4
        case ('frontend_ast_v1_storage_sequence_5'); mir_source_rule_value = source_rule_frontend_ast_v1_storage_sequence_5
        case ('frontend_ast_v2_execution_part'); mir_source_rule_value = source_rule_frontend_ast_v2_execution_part
        case default; mir_source_rule_value = ''
        end select
    end function mir_source_rule_value

    integer(int32) function mir_frontend_ast_v1_integer_expression_route(expression)
        character(len=*), intent(in) :: expression

        select case (trim(expression))
        case ('( binary-expr ( operator + ) ( left 1 ) ( right 2 ) )'); mir_frontend_ast_v1_integer_expression_route = 1_int32
        case ('(assignment-expression (kind binary-expression) (operator +) (left-operand x) (right-operand 1))'); mir_frontend_ast_v1_integer_expression_route = 2_int32
        case ('( binary-expr ( operator * ) ( left 2 ) ( right 3 ) )'); mir_frontend_ast_v1_integer_expression_route = 3_int32
        case ('( binary-expr ( operator / ) ( left 6 ) ( right 2 ) )'); mir_frontend_ast_v1_integer_expression_route = 4_int32
        case ('( binary-expr ( operator – ) ( left 5 ) ( right 3 ) )'); mir_frontend_ast_v1_integer_expression_route = 5_int32
        case ('(assignment-sequence (assignment-count 2) (first x ( integer-literal 7 )) (second x (assignment-expression (kind binary-expression) (operator +) (left-operand x) (right-operand 1))))'); mir_frontend_ast_v1_integer_expression_route = 6_int32
        case ('(assignment-sequence (assignment-count 3) (first x ( integer-literal 7 )) (second x (assignment-expression (kind binary-expression) (operator +) (left-operand x) (right-operand 1))) (third x (assignment-expression (kind binary-expression) (operator +) (left-operand x) (right-operand 1))))'); mir_frontend_ast_v1_integer_expression_route = 7_int32
        case ('(assignment-sequence (assignment-count 4) (first x ( integer-literal 7 )) (second x (assignment-expression (kind binary-expression) (operator +) (left-operand x) (right-operand 1))) (third x (assignment-expression (kind binary-expression) (operator +) (left-operand x) (right-operand 1))) (fourth x (assignment-expression (kind binary-expression) (operator +) (left-operand x) (right-operand 1))))'); mir_frontend_ast_v1_integer_expression_route = 8_int32
        case ('(assignment-sequence (assignment-count 5) (first x ( integer-literal 7 )) (second x (assignment-expression (kind binary-expression) (operator +) (left-operand x) (right-operand 1))) (third x (assignment-expression (kind binary-expression) (operator +) (left-operand x) (right-operand 1))) (fourth x (assignment-expression (kind binary-expression) (operator +) (left-operand x) (right-operand 1))) (fifth x (assignment-expression (kind binary-expression) (operator +) (left-operand x) (right-operand 1))))'); mir_frontend_ast_v1_integer_expression_route = 9_int32
        case ('(execution-part (assignment-sequence (assignment-count 2) (assignment x ( integer-literal 7 )) (assignment x (assignment-expression (kind binary-expression) (operator +) (left-operand x) (right-operand 1)))) )'); mir_frontend_ast_v1_integer_expression_route = 10_int32
        case default; mir_frontend_ast_v1_integer_expression_route = 0_int32
        end select
    end function mir_frontend_ast_v1_integer_expression_route

    integer(int32) function mir_frontend_ast_v1_integer_expression_instruction_count(route)
        integer(int32), intent(in) :: route

        select case (route)
        case (1_int32); mir_frontend_ast_v1_integer_expression_instruction_count = instruction_shape_frontend_ast_v1_int_expr_assign_count
        case (2_int32); mir_frontend_ast_v1_integer_expression_instruction_count = instruction_shape_frontend_ast_v1_int_var_assign_count
        case (3_int32); mir_frontend_ast_v1_integer_expression_instruction_count = instruction_shape_frontend_ast_v1_int_mul_assign_count
        case (4_int32); mir_frontend_ast_v1_integer_expression_instruction_count = instruction_shape_frontend_ast_v1_int_div_assign_count
        case (5_int32); mir_frontend_ast_v1_integer_expression_instruction_count = instruction_shape_frontend_ast_v1_int_sub_assign_count
        case (6_int32); mir_frontend_ast_v1_integer_expression_instruction_count = instruction_shape_frontend_ast_v1_int_seq_count
        case (7_int32); mir_frontend_ast_v1_integer_expression_instruction_count = instruction_shape_frontend_ast_v1_int_seq_3_count
        case (8_int32); mir_frontend_ast_v1_integer_expression_instruction_count = instruction_shape_frontend_ast_v1_int_seq_4_count
        case (9_int32); mir_frontend_ast_v1_integer_expression_instruction_count = instruction_shape_frontend_ast_v1_int_seq_5_count
        case (10_int32); mir_frontend_ast_v1_integer_expression_instruction_count = instruction_shape_frontend_ast_v2_int_exec_count
        case default; mir_frontend_ast_v1_integer_expression_instruction_count = 0_int32
        end select
    end function mir_frontend_ast_v1_integer_expression_instruction_count

    integer(int32) function mir_frontend_ast_v1_integer_expression_opcode(route, index)
        integer(int32), intent(in) :: route, index

        mir_frontend_ast_v1_integer_expression_opcode = 0_int32
        select case (route)
        case (1_int32)
            select case (index)
            case (0_int32); mir_frontend_ast_v1_integer_expression_opcode = instruction_shape_frontend_ast_v1_int_expr_assign_opcode_0
            case (1_int32); mir_frontend_ast_v1_integer_expression_opcode = instruction_shape_frontend_ast_v1_int_expr_assign_opcode_1
            case (2_int32); mir_frontend_ast_v1_integer_expression_opcode = instruction_shape_frontend_ast_v1_int_expr_assign_opcode_2
            case (3_int32); mir_frontend_ast_v1_integer_expression_opcode = instruction_shape_frontend_ast_v1_int_expr_assign_opcode_3
            case (4_int32); mir_frontend_ast_v1_integer_expression_opcode = instruction_shape_frontend_ast_v1_int_expr_assign_opcode_4
            end select
        case (2_int32)
            select case (index)
            case (0_int32); mir_frontend_ast_v1_integer_expression_opcode = instruction_shape_frontend_ast_v1_int_var_assign_opcode_0
            case (1_int32); mir_frontend_ast_v1_integer_expression_opcode = instruction_shape_frontend_ast_v1_int_var_assign_opcode_1
            case (2_int32); mir_frontend_ast_v1_integer_expression_opcode = instruction_shape_frontend_ast_v1_int_var_assign_opcode_2
            case (3_int32); mir_frontend_ast_v1_integer_expression_opcode = instruction_shape_frontend_ast_v1_int_var_assign_opcode_3
            case (4_int32); mir_frontend_ast_v1_integer_expression_opcode = instruction_shape_frontend_ast_v1_int_var_assign_opcode_4
            end select
        case (3_int32)
            select case (index)
            case (0_int32); mir_frontend_ast_v1_integer_expression_opcode = instruction_shape_frontend_ast_v1_int_mul_assign_opcode_0
            case (1_int32); mir_frontend_ast_v1_integer_expression_opcode = instruction_shape_frontend_ast_v1_int_mul_assign_opcode_1
            case (2_int32); mir_frontend_ast_v1_integer_expression_opcode = instruction_shape_frontend_ast_v1_int_mul_assign_opcode_2
            case (3_int32); mir_frontend_ast_v1_integer_expression_opcode = instruction_shape_frontend_ast_v1_int_mul_assign_opcode_3
            case (4_int32); mir_frontend_ast_v1_integer_expression_opcode = instruction_shape_frontend_ast_v1_int_mul_assign_opcode_4
            end select
        case (4_int32)
            select case (index)
            case (0_int32); mir_frontend_ast_v1_integer_expression_opcode = instruction_shape_frontend_ast_v1_int_div_assign_opcode_0
            case (1_int32); mir_frontend_ast_v1_integer_expression_opcode = instruction_shape_frontend_ast_v1_int_div_assign_opcode_1
            case (2_int32); mir_frontend_ast_v1_integer_expression_opcode = instruction_shape_frontend_ast_v1_int_div_assign_opcode_2
            case (3_int32); mir_frontend_ast_v1_integer_expression_opcode = instruction_shape_frontend_ast_v1_int_div_assign_opcode_3
            case (4_int32); mir_frontend_ast_v1_integer_expression_opcode = instruction_shape_frontend_ast_v1_int_div_assign_opcode_4
            end select
        case (5_int32)
            select case (index)
            case (0_int32); mir_frontend_ast_v1_integer_expression_opcode = instruction_shape_frontend_ast_v1_int_sub_assign_opcode_0
            case (1_int32); mir_frontend_ast_v1_integer_expression_opcode = instruction_shape_frontend_ast_v1_int_sub_assign_opcode_1
            case (2_int32); mir_frontend_ast_v1_integer_expression_opcode = instruction_shape_frontend_ast_v1_int_sub_assign_opcode_2
            case (3_int32); mir_frontend_ast_v1_integer_expression_opcode = instruction_shape_frontend_ast_v1_int_sub_assign_opcode_3
            case (4_int32); mir_frontend_ast_v1_integer_expression_opcode = instruction_shape_frontend_ast_v1_int_sub_assign_opcode_4
            end select
        case (6_int32)
            select case (index)
            case (0_int32); mir_frontend_ast_v1_integer_expression_opcode = instruction_shape_frontend_ast_v1_int_seq_opcode_0
            case (1_int32); mir_frontend_ast_v1_integer_expression_opcode = instruction_shape_frontend_ast_v1_int_seq_opcode_1
            case (2_int32); mir_frontend_ast_v1_integer_expression_opcode = instruction_shape_frontend_ast_v1_int_seq_opcode_2
            case (3_int32); mir_frontend_ast_v1_integer_expression_opcode = instruction_shape_frontend_ast_v1_int_seq_opcode_3
            case (4_int32); mir_frontend_ast_v1_integer_expression_opcode = instruction_shape_frontend_ast_v1_int_seq_opcode_4
            case (5_int32); mir_frontend_ast_v1_integer_expression_opcode = instruction_shape_frontend_ast_v1_int_seq_opcode_5
            case (6_int32); mir_frontend_ast_v1_integer_expression_opcode = instruction_shape_frontend_ast_v1_int_seq_opcode_6
            end select
        case (7_int32)
            select case (index)
            case (0_int32); mir_frontend_ast_v1_integer_expression_opcode = instruction_shape_frontend_ast_v1_int_seq_3_opcode_0
            case (1_int32); mir_frontend_ast_v1_integer_expression_opcode = instruction_shape_frontend_ast_v1_int_seq_3_opcode_1
            case (2_int32); mir_frontend_ast_v1_integer_expression_opcode = instruction_shape_frontend_ast_v1_int_seq_3_opcode_2
            case (3_int32); mir_frontend_ast_v1_integer_expression_opcode = instruction_shape_frontend_ast_v1_int_seq_3_opcode_3
            case (4_int32); mir_frontend_ast_v1_integer_expression_opcode = instruction_shape_frontend_ast_v1_int_seq_3_opcode_4
            case (5_int32); mir_frontend_ast_v1_integer_expression_opcode = instruction_shape_frontend_ast_v1_int_seq_3_opcode_5
            case (6_int32); mir_frontend_ast_v1_integer_expression_opcode = instruction_shape_frontend_ast_v1_int_seq_3_opcode_6
            case (7_int32); mir_frontend_ast_v1_integer_expression_opcode = instruction_shape_frontend_ast_v1_int_seq_3_opcode_7
            case (8_int32); mir_frontend_ast_v1_integer_expression_opcode = instruction_shape_frontend_ast_v1_int_seq_3_opcode_8
            case (9_int32); mir_frontend_ast_v1_integer_expression_opcode = instruction_shape_frontend_ast_v1_int_seq_3_opcode_9
            case (10_int32); mir_frontend_ast_v1_integer_expression_opcode = instruction_shape_frontend_ast_v1_int_seq_3_opcode_10
            end select
        case (8_int32)
            select case (index)
            case (0_int32); mir_frontend_ast_v1_integer_expression_opcode = instruction_shape_frontend_ast_v1_int_seq_4_opcode_0
            case (1_int32); mir_frontend_ast_v1_integer_expression_opcode = instruction_shape_frontend_ast_v1_int_seq_4_opcode_1
            case (2_int32); mir_frontend_ast_v1_integer_expression_opcode = instruction_shape_frontend_ast_v1_int_seq_4_opcode_2
            case (3_int32); mir_frontend_ast_v1_integer_expression_opcode = instruction_shape_frontend_ast_v1_int_seq_4_opcode_3
            case (4_int32); mir_frontend_ast_v1_integer_expression_opcode = instruction_shape_frontend_ast_v1_int_seq_4_opcode_4
            case (5_int32); mir_frontend_ast_v1_integer_expression_opcode = instruction_shape_frontend_ast_v1_int_seq_4_opcode_5
            case (6_int32); mir_frontend_ast_v1_integer_expression_opcode = instruction_shape_frontend_ast_v1_int_seq_4_opcode_6
            case (7_int32); mir_frontend_ast_v1_integer_expression_opcode = instruction_shape_frontend_ast_v1_int_seq_4_opcode_7
            case (8_int32); mir_frontend_ast_v1_integer_expression_opcode = instruction_shape_frontend_ast_v1_int_seq_4_opcode_8
            case (9_int32); mir_frontend_ast_v1_integer_expression_opcode = instruction_shape_frontend_ast_v1_int_seq_4_opcode_9
            case (10_int32); mir_frontend_ast_v1_integer_expression_opcode = instruction_shape_frontend_ast_v1_int_seq_4_opcode_10
            case (11_int32); mir_frontend_ast_v1_integer_expression_opcode = instruction_shape_frontend_ast_v1_int_seq_4_opcode_11
            case (12_int32); mir_frontend_ast_v1_integer_expression_opcode = instruction_shape_frontend_ast_v1_int_seq_4_opcode_12
            case (13_int32); mir_frontend_ast_v1_integer_expression_opcode = instruction_shape_frontend_ast_v1_int_seq_4_opcode_13
            case (14_int32); mir_frontend_ast_v1_integer_expression_opcode = instruction_shape_frontend_ast_v1_int_seq_4_opcode_14
            end select
        case (9_int32)
            select case (index)
            case (0_int32); mir_frontend_ast_v1_integer_expression_opcode = instruction_shape_frontend_ast_v1_int_seq_5_opcode_0
            case (1_int32); mir_frontend_ast_v1_integer_expression_opcode = instruction_shape_frontend_ast_v1_int_seq_5_opcode_1
            case (2_int32); mir_frontend_ast_v1_integer_expression_opcode = instruction_shape_frontend_ast_v1_int_seq_5_opcode_2
            case (3_int32); mir_frontend_ast_v1_integer_expression_opcode = instruction_shape_frontend_ast_v1_int_seq_5_opcode_3
            case (4_int32); mir_frontend_ast_v1_integer_expression_opcode = instruction_shape_frontend_ast_v1_int_seq_5_opcode_4
            case (5_int32); mir_frontend_ast_v1_integer_expression_opcode = instruction_shape_frontend_ast_v1_int_seq_5_opcode_5
            case (6_int32); mir_frontend_ast_v1_integer_expression_opcode = instruction_shape_frontend_ast_v1_int_seq_5_opcode_6
            case (7_int32); mir_frontend_ast_v1_integer_expression_opcode = instruction_shape_frontend_ast_v1_int_seq_5_opcode_7
            case (8_int32); mir_frontend_ast_v1_integer_expression_opcode = instruction_shape_frontend_ast_v1_int_seq_5_opcode_8
            case (9_int32); mir_frontend_ast_v1_integer_expression_opcode = instruction_shape_frontend_ast_v1_int_seq_5_opcode_9
            case (10_int32); mir_frontend_ast_v1_integer_expression_opcode = instruction_shape_frontend_ast_v1_int_seq_5_opcode_10
            case (11_int32); mir_frontend_ast_v1_integer_expression_opcode = instruction_shape_frontend_ast_v1_int_seq_5_opcode_11
            case (12_int32); mir_frontend_ast_v1_integer_expression_opcode = instruction_shape_frontend_ast_v1_int_seq_5_opcode_12
            case (13_int32); mir_frontend_ast_v1_integer_expression_opcode = instruction_shape_frontend_ast_v1_int_seq_5_opcode_13
            case (14_int32); mir_frontend_ast_v1_integer_expression_opcode = instruction_shape_frontend_ast_v1_int_seq_5_opcode_14
            case (15_int32); mir_frontend_ast_v1_integer_expression_opcode = instruction_shape_frontend_ast_v1_int_seq_5_opcode_15
            case (16_int32); mir_frontend_ast_v1_integer_expression_opcode = instruction_shape_frontend_ast_v1_int_seq_5_opcode_16
            case (17_int32); mir_frontend_ast_v1_integer_expression_opcode = instruction_shape_frontend_ast_v1_int_seq_5_opcode_17
            case (18_int32); mir_frontend_ast_v1_integer_expression_opcode = instruction_shape_frontend_ast_v1_int_seq_5_opcode_18
            end select
        case (10_int32)
            select case (index)
            case (0_int32); mir_frontend_ast_v1_integer_expression_opcode = instruction_shape_frontend_ast_v2_int_exec_opcode_0
            case (1_int32); mir_frontend_ast_v1_integer_expression_opcode = instruction_shape_frontend_ast_v2_int_exec_opcode_1
            case (2_int32); mir_frontend_ast_v1_integer_expression_opcode = instruction_shape_frontend_ast_v2_int_exec_opcode_2
            case (3_int32); mir_frontend_ast_v1_integer_expression_opcode = instruction_shape_frontend_ast_v2_int_exec_opcode_3
            case (4_int32); mir_frontend_ast_v1_integer_expression_opcode = instruction_shape_frontend_ast_v2_int_exec_opcode_4
            case (5_int32); mir_frontend_ast_v1_integer_expression_opcode = instruction_shape_frontend_ast_v2_int_exec_opcode_5
            case (6_int32); mir_frontend_ast_v1_integer_expression_opcode = instruction_shape_frontend_ast_v2_int_exec_opcode_6
            end select
        end select
    end function mir_frontend_ast_v1_integer_expression_opcode

    integer(int32) function mir_frontend_ast_v1_integer_expression_result_kind(route)
        integer(int32), intent(in) :: route

        mir_frontend_ast_v1_integer_expression_result_kind = 0_int32
        select case (route)
        case (1_int32); mir_frontend_ast_v1_integer_expression_result_kind = instruction_shape_frontend_ast_v1_int_expr_assign_result_kind
        case (2_int32); mir_frontend_ast_v1_integer_expression_result_kind = instruction_shape_frontend_ast_v1_int_var_assign_result_kind
        case (3_int32); mir_frontend_ast_v1_integer_expression_result_kind = instruction_shape_frontend_ast_v1_int_mul_assign_result_kind
        case (4_int32); mir_frontend_ast_v1_integer_expression_result_kind = instruction_shape_frontend_ast_v1_int_div_assign_result_kind
        case (5_int32); mir_frontend_ast_v1_integer_expression_result_kind = instruction_shape_frontend_ast_v1_int_sub_assign_result_kind
        case (6_int32); mir_frontend_ast_v1_integer_expression_result_kind = instruction_shape_frontend_ast_v1_int_seq_result_kind
        case (7_int32); mir_frontend_ast_v1_integer_expression_result_kind = instruction_shape_frontend_ast_v1_int_seq_3_result_kind
        case (8_int32); mir_frontend_ast_v1_integer_expression_result_kind = instruction_shape_frontend_ast_v1_int_seq_4_result_kind
        case (9_int32); mir_frontend_ast_v1_integer_expression_result_kind = instruction_shape_frontend_ast_v1_int_seq_5_result_kind
        case (10_int32); mir_frontend_ast_v1_integer_expression_result_kind = instruction_shape_frontend_ast_v2_int_exec_result_kind
        end select
    end function mir_frontend_ast_v1_integer_expression_result_kind

    character(len=32) function mir_frontend_ast_v1_integer_expression_result_type(route)
        integer(int32), intent(in) :: route

        mir_frontend_ast_v1_integer_expression_result_type = ''
        select case (route)
        case (1_int32); mir_frontend_ast_v1_integer_expression_result_type = instruction_shape_frontend_ast_v1_int_expr_assign_result_type
        case (2_int32); mir_frontend_ast_v1_integer_expression_result_type = instruction_shape_frontend_ast_v1_int_var_assign_result_type
        case (3_int32); mir_frontend_ast_v1_integer_expression_result_type = instruction_shape_frontend_ast_v1_int_mul_assign_result_type
        case (4_int32); mir_frontend_ast_v1_integer_expression_result_type = instruction_shape_frontend_ast_v1_int_div_assign_result_type
        case (5_int32); mir_frontend_ast_v1_integer_expression_result_type = instruction_shape_frontend_ast_v1_int_sub_assign_result_type
        case (6_int32); mir_frontend_ast_v1_integer_expression_result_type = instruction_shape_frontend_ast_v1_int_seq_result_type
        case (7_int32); mir_frontend_ast_v1_integer_expression_result_type = instruction_shape_frontend_ast_v1_int_seq_3_result_type
        case (8_int32); mir_frontend_ast_v1_integer_expression_result_type = instruction_shape_frontend_ast_v1_int_seq_4_result_type
        case (9_int32); mir_frontend_ast_v1_integer_expression_result_type = instruction_shape_frontend_ast_v1_int_seq_5_result_type
        case (10_int32); mir_frontend_ast_v1_integer_expression_result_type = instruction_shape_frontend_ast_v2_int_exec_result_type
        end select
    end function mir_frontend_ast_v1_integer_expression_result_type

    character(len=64) function mir_frontend_ast_v1_integer_expression_source_rule(route)
        integer(int32), intent(in) :: route

        mir_frontend_ast_v1_integer_expression_source_rule = ''
        select case (route)
        case (1_int32); mir_frontend_ast_v1_integer_expression_source_rule = instruction_shape_frontend_ast_v1_int_expr_assign_source_rule
        case (2_int32); mir_frontend_ast_v1_integer_expression_source_rule = instruction_shape_frontend_ast_v1_int_var_assign_source_rule
        case (3_int32); mir_frontend_ast_v1_integer_expression_source_rule = instruction_shape_frontend_ast_v1_int_mul_assign_source_rule
        case (4_int32); mir_frontend_ast_v1_integer_expression_source_rule = instruction_shape_frontend_ast_v1_int_div_assign_source_rule
        case (5_int32); mir_frontend_ast_v1_integer_expression_source_rule = instruction_shape_frontend_ast_v1_int_sub_assign_source_rule
        case (6_int32); mir_frontend_ast_v1_integer_expression_source_rule = instruction_shape_frontend_ast_v1_int_seq_source_rule
        case (7_int32); mir_frontend_ast_v1_integer_expression_source_rule = instruction_shape_frontend_ast_v1_int_seq_3_source_rule
        case (8_int32); mir_frontend_ast_v1_integer_expression_source_rule = instruction_shape_frontend_ast_v1_int_seq_4_source_rule
        case (9_int32); mir_frontend_ast_v1_integer_expression_source_rule = instruction_shape_frontend_ast_v1_int_seq_5_source_rule
        case (10_int32); mir_frontend_ast_v1_integer_expression_source_rule = instruction_shape_frontend_ast_v2_int_exec_source_rule
        end select
    end function mir_frontend_ast_v1_integer_expression_source_rule

    integer(int32) function mir_frontend_ast_v1_integer_expression_literal_value(route, index)
        integer(int32), intent(in) :: route, index

        mir_frontend_ast_v1_integer_expression_literal_value = 0_int32
        select case (route)
        case (1_int32)
            select case (index)
            case (0_int32); mir_frontend_ast_v1_integer_expression_literal_value = 1_int32
            case (1_int32); mir_frontend_ast_v1_integer_expression_literal_value = 2_int32
            end select
        case (2_int32)
            select case (index)
            case (0_int32); mir_frontend_ast_v1_integer_expression_literal_value = 1_int32
            end select
        case (3_int32)
            select case (index)
            case (0_int32); mir_frontend_ast_v1_integer_expression_literal_value = 2_int32
            case (1_int32); mir_frontend_ast_v1_integer_expression_literal_value = 3_int32
            end select
        case (4_int32)
            select case (index)
            case (0_int32); mir_frontend_ast_v1_integer_expression_literal_value = 6_int32
            case (1_int32); mir_frontend_ast_v1_integer_expression_literal_value = 2_int32
            end select
        case (5_int32)
            select case (index)
            case (0_int32); mir_frontend_ast_v1_integer_expression_literal_value = 5_int32
            case (1_int32); mir_frontend_ast_v1_integer_expression_literal_value = 3_int32
            end select
        case (6_int32)
            select case (index)
            case (0_int32); mir_frontend_ast_v1_integer_expression_literal_value = 7_int32
            case (1_int32); mir_frontend_ast_v1_integer_expression_literal_value = 1_int32
            end select
        case (7_int32)
            select case (index)
            case (0_int32); mir_frontend_ast_v1_integer_expression_literal_value = 7_int32
            case (1_int32); mir_frontend_ast_v1_integer_expression_literal_value = 1_int32
            case (2_int32); mir_frontend_ast_v1_integer_expression_literal_value = 1_int32
            end select
        case (8_int32)
            select case (index)
            case (0_int32); mir_frontend_ast_v1_integer_expression_literal_value = 7_int32
            case (1_int32); mir_frontend_ast_v1_integer_expression_literal_value = 1_int32
            case (2_int32); mir_frontend_ast_v1_integer_expression_literal_value = 1_int32
            case (3_int32); mir_frontend_ast_v1_integer_expression_literal_value = 1_int32
            end select
        case (9_int32)
            select case (index)
            case (0_int32); mir_frontend_ast_v1_integer_expression_literal_value = 7_int32
            case (1_int32); mir_frontend_ast_v1_integer_expression_literal_value = 1_int32
            case (2_int32); mir_frontend_ast_v1_integer_expression_literal_value = 1_int32
            case (3_int32); mir_frontend_ast_v1_integer_expression_literal_value = 1_int32
            case (4_int32); mir_frontend_ast_v1_integer_expression_literal_value = 1_int32
            end select
        case (10_int32)
            select case (index)
            case (0_int32); mir_frontend_ast_v1_integer_expression_literal_value = 7_int32
            case (1_int32); mir_frontend_ast_v1_integer_expression_literal_value = 1_int32
            end select
        end select
    end function mir_frontend_ast_v1_integer_expression_literal_value

    integer(int32) function mir_frontend_ast_v1_integer_expression_result_id(route, index)
        integer(int32), intent(in) :: route, index

        mir_frontend_ast_v1_integer_expression_result_id = -1_int32
        select case (route)
        case (1_int32)
            select case (index)
            case (0_int32); mir_frontend_ast_v1_integer_expression_result_id = 0_int32
            case (1_int32); mir_frontend_ast_v1_integer_expression_result_id = 1_int32
            case (2_int32); mir_frontend_ast_v1_integer_expression_result_id = 2_int32
            case (3_int32); mir_frontend_ast_v1_integer_expression_result_id = 2_int32
            case (4_int32); mir_frontend_ast_v1_integer_expression_result_id = 2_int32
            end select
        case (2_int32)
            select case (index)
            case (0_int32); mir_frontend_ast_v1_integer_expression_result_id = 0_int32
            case (1_int32); mir_frontend_ast_v1_integer_expression_result_id = 1_int32
            case (2_int32); mir_frontend_ast_v1_integer_expression_result_id = 2_int32
            case (3_int32); mir_frontend_ast_v1_integer_expression_result_id = 2_int32
            case (4_int32); mir_frontend_ast_v1_integer_expression_result_id = 2_int32
            end select
        case (3_int32)
            select case (index)
            case (0_int32); mir_frontend_ast_v1_integer_expression_result_id = 0_int32
            case (1_int32); mir_frontend_ast_v1_integer_expression_result_id = 1_int32
            case (2_int32); mir_frontend_ast_v1_integer_expression_result_id = 2_int32
            case (3_int32); mir_frontend_ast_v1_integer_expression_result_id = 2_int32
            case (4_int32); mir_frontend_ast_v1_integer_expression_result_id = 2_int32
            end select
        case (4_int32)
            select case (index)
            case (0_int32); mir_frontend_ast_v1_integer_expression_result_id = 0_int32
            case (1_int32); mir_frontend_ast_v1_integer_expression_result_id = 1_int32
            case (2_int32); mir_frontend_ast_v1_integer_expression_result_id = 2_int32
            case (3_int32); mir_frontend_ast_v1_integer_expression_result_id = 2_int32
            case (4_int32); mir_frontend_ast_v1_integer_expression_result_id = 2_int32
            end select
        case (5_int32)
            select case (index)
            case (0_int32); mir_frontend_ast_v1_integer_expression_result_id = 0_int32
            case (1_int32); mir_frontend_ast_v1_integer_expression_result_id = 1_int32
            case (2_int32); mir_frontend_ast_v1_integer_expression_result_id = 2_int32
            case (3_int32); mir_frontend_ast_v1_integer_expression_result_id = 2_int32
            case (4_int32); mir_frontend_ast_v1_integer_expression_result_id = 2_int32
            end select
        case (6_int32)
            select case (index)
            case (0_int32); mir_frontend_ast_v1_integer_expression_result_id = 0_int32
            case (1_int32); mir_frontend_ast_v1_integer_expression_result_id = 1_int32
            case (2_int32); mir_frontend_ast_v1_integer_expression_result_id = 2_int32
            case (3_int32); mir_frontend_ast_v1_integer_expression_result_id = 3_int32
            case (4_int32); mir_frontend_ast_v1_integer_expression_result_id = 4_int32
            case (5_int32); mir_frontend_ast_v1_integer_expression_result_id = 4_int32
            case (6_int32); mir_frontend_ast_v1_integer_expression_result_id = 4_int32
            end select
        case (7_int32)
            select case (index)
            case (0_int32); mir_frontend_ast_v1_integer_expression_result_id = 0_int32
            case (1_int32); mir_frontend_ast_v1_integer_expression_result_id = 1_int32
            case (2_int32); mir_frontend_ast_v1_integer_expression_result_id = 2_int32
            case (3_int32); mir_frontend_ast_v1_integer_expression_result_id = 3_int32
            case (4_int32); mir_frontend_ast_v1_integer_expression_result_id = 4_int32
            case (5_int32); mir_frontend_ast_v1_integer_expression_result_id = 4_int32
            case (6_int32); mir_frontend_ast_v1_integer_expression_result_id = 6_int32
            case (7_int32); mir_frontend_ast_v1_integer_expression_result_id = 7_int32
            case (8_int32); mir_frontend_ast_v1_integer_expression_result_id = 8_int32
            case (9_int32); mir_frontend_ast_v1_integer_expression_result_id = 8_int32
            case (10_int32); mir_frontend_ast_v1_integer_expression_result_id = 8_int32
            end select
        case (8_int32)
            select case (index)
            case (0_int32); mir_frontend_ast_v1_integer_expression_result_id = 0_int32
            case (1_int32); mir_frontend_ast_v1_integer_expression_result_id = 1_int32
            case (2_int32); mir_frontend_ast_v1_integer_expression_result_id = 2_int32
            case (3_int32); mir_frontend_ast_v1_integer_expression_result_id = 3_int32
            case (4_int32); mir_frontend_ast_v1_integer_expression_result_id = 4_int32
            case (5_int32); mir_frontend_ast_v1_integer_expression_result_id = 4_int32
            case (6_int32); mir_frontend_ast_v1_integer_expression_result_id = 6_int32
            case (7_int32); mir_frontend_ast_v1_integer_expression_result_id = 7_int32
            case (8_int32); mir_frontend_ast_v1_integer_expression_result_id = 8_int32
            case (9_int32); mir_frontend_ast_v1_integer_expression_result_id = 8_int32
            case (10_int32); mir_frontend_ast_v1_integer_expression_result_id = 10_int32
            case (11_int32); mir_frontend_ast_v1_integer_expression_result_id = 11_int32
            case (12_int32); mir_frontend_ast_v1_integer_expression_result_id = 12_int32
            case (13_int32); mir_frontend_ast_v1_integer_expression_result_id = 12_int32
            case (14_int32); mir_frontend_ast_v1_integer_expression_result_id = 12_int32
            end select
        case (9_int32)
            select case (index)
            case (0_int32); mir_frontend_ast_v1_integer_expression_result_id = 0_int32
            case (1_int32); mir_frontend_ast_v1_integer_expression_result_id = 1_int32
            case (2_int32); mir_frontend_ast_v1_integer_expression_result_id = 2_int32
            case (3_int32); mir_frontend_ast_v1_integer_expression_result_id = 3_int32
            case (4_int32); mir_frontend_ast_v1_integer_expression_result_id = 4_int32
            case (5_int32); mir_frontend_ast_v1_integer_expression_result_id = 4_int32
            case (6_int32); mir_frontend_ast_v1_integer_expression_result_id = 6_int32
            case (7_int32); mir_frontend_ast_v1_integer_expression_result_id = 7_int32
            case (8_int32); mir_frontend_ast_v1_integer_expression_result_id = 8_int32
            case (9_int32); mir_frontend_ast_v1_integer_expression_result_id = 8_int32
            case (10_int32); mir_frontend_ast_v1_integer_expression_result_id = 10_int32
            case (11_int32); mir_frontend_ast_v1_integer_expression_result_id = 11_int32
            case (12_int32); mir_frontend_ast_v1_integer_expression_result_id = 12_int32
            case (13_int32); mir_frontend_ast_v1_integer_expression_result_id = 12_int32
            case (14_int32); mir_frontend_ast_v1_integer_expression_result_id = 14_int32
            case (15_int32); mir_frontend_ast_v1_integer_expression_result_id = 15_int32
            case (16_int32); mir_frontend_ast_v1_integer_expression_result_id = 16_int32
            case (17_int32); mir_frontend_ast_v1_integer_expression_result_id = 16_int32
            case (18_int32); mir_frontend_ast_v1_integer_expression_result_id = 16_int32
            end select
        case (10_int32)
            select case (index)
            case (0_int32); mir_frontend_ast_v1_integer_expression_result_id = 0_int32
            case (1_int32); mir_frontend_ast_v1_integer_expression_result_id = 1_int32
            case (2_int32); mir_frontend_ast_v1_integer_expression_result_id = 2_int32
            case (3_int32); mir_frontend_ast_v1_integer_expression_result_id = 3_int32
            case (4_int32); mir_frontend_ast_v1_integer_expression_result_id = 4_int32
            case (5_int32); mir_frontend_ast_v1_integer_expression_result_id = 4_int32
            case (6_int32); mir_frontend_ast_v1_integer_expression_result_id = 4_int32
            end select
        end select
    end function mir_frontend_ast_v1_integer_expression_result_id

    character(len=64) function mir_frontend_ast_v1_integer_expression_storage_key(route, index)
        integer(int32), intent(in) :: route, index

        mir_frontend_ast_v1_integer_expression_storage_key = ''
        select case (route)
        case (1_int32)
            select case (index)
            end select
        case (2_int32)
            select case (index)
            case (0_int32); mir_frontend_ast_v1_integer_expression_storage_key = 'x'
            case (1_int32); mir_frontend_ast_v1_integer_expression_storage_key = ''
            case (2_int32); mir_frontend_ast_v1_integer_expression_storage_key = ''
            case (3_int32); mir_frontend_ast_v1_integer_expression_storage_key = 'x'
            case (4_int32); mir_frontend_ast_v1_integer_expression_storage_key = ''
            end select
        case (3_int32)
            select case (index)
            end select
        case (4_int32)
            select case (index)
            end select
        case (5_int32)
            select case (index)
            end select
        case (6_int32)
            select case (index)
            case (0_int32); mir_frontend_ast_v1_integer_expression_storage_key = ''
            case (1_int32); mir_frontend_ast_v1_integer_expression_storage_key = 'x'
            case (2_int32); mir_frontend_ast_v1_integer_expression_storage_key = 'x'
            case (3_int32); mir_frontend_ast_v1_integer_expression_storage_key = ''
            case (4_int32); mir_frontend_ast_v1_integer_expression_storage_key = ''
            case (5_int32); mir_frontend_ast_v1_integer_expression_storage_key = 'x'
            case (6_int32); mir_frontend_ast_v1_integer_expression_storage_key = ''
            end select
        case (7_int32)
            select case (index)
            case (0_int32); mir_frontend_ast_v1_integer_expression_storage_key = ''
            case (1_int32); mir_frontend_ast_v1_integer_expression_storage_key = 'x'
            case (2_int32); mir_frontend_ast_v1_integer_expression_storage_key = 'x'
            case (3_int32); mir_frontend_ast_v1_integer_expression_storage_key = ''
            case (4_int32); mir_frontend_ast_v1_integer_expression_storage_key = ''
            case (5_int32); mir_frontend_ast_v1_integer_expression_storage_key = 'x'
            case (6_int32); mir_frontend_ast_v1_integer_expression_storage_key = 'x'
            case (7_int32); mir_frontend_ast_v1_integer_expression_storage_key = ''
            case (8_int32); mir_frontend_ast_v1_integer_expression_storage_key = ''
            case (9_int32); mir_frontend_ast_v1_integer_expression_storage_key = 'x'
            case (10_int32); mir_frontend_ast_v1_integer_expression_storage_key = ''
            end select
        case (8_int32)
            select case (index)
            case (0_int32); mir_frontend_ast_v1_integer_expression_storage_key = ''
            case (1_int32); mir_frontend_ast_v1_integer_expression_storage_key = 'x'
            case (2_int32); mir_frontend_ast_v1_integer_expression_storage_key = 'x'
            case (3_int32); mir_frontend_ast_v1_integer_expression_storage_key = ''
            case (4_int32); mir_frontend_ast_v1_integer_expression_storage_key = ''
            case (5_int32); mir_frontend_ast_v1_integer_expression_storage_key = 'x'
            case (6_int32); mir_frontend_ast_v1_integer_expression_storage_key = 'x'
            case (7_int32); mir_frontend_ast_v1_integer_expression_storage_key = ''
            case (8_int32); mir_frontend_ast_v1_integer_expression_storage_key = ''
            case (9_int32); mir_frontend_ast_v1_integer_expression_storage_key = 'x'
            case (10_int32); mir_frontend_ast_v1_integer_expression_storage_key = 'x'
            case (11_int32); mir_frontend_ast_v1_integer_expression_storage_key = ''
            case (12_int32); mir_frontend_ast_v1_integer_expression_storage_key = ''
            case (13_int32); mir_frontend_ast_v1_integer_expression_storage_key = 'x'
            case (14_int32); mir_frontend_ast_v1_integer_expression_storage_key = ''
            end select
        case (9_int32)
            select case (index)
            case (0_int32); mir_frontend_ast_v1_integer_expression_storage_key = ''
            case (1_int32); mir_frontend_ast_v1_integer_expression_storage_key = 'x'
            case (2_int32); mir_frontend_ast_v1_integer_expression_storage_key = 'x'
            case (3_int32); mir_frontend_ast_v1_integer_expression_storage_key = ''
            case (4_int32); mir_frontend_ast_v1_integer_expression_storage_key = ''
            case (5_int32); mir_frontend_ast_v1_integer_expression_storage_key = 'x'
            case (6_int32); mir_frontend_ast_v1_integer_expression_storage_key = 'x'
            case (7_int32); mir_frontend_ast_v1_integer_expression_storage_key = ''
            case (8_int32); mir_frontend_ast_v1_integer_expression_storage_key = ''
            case (9_int32); mir_frontend_ast_v1_integer_expression_storage_key = 'x'
            case (10_int32); mir_frontend_ast_v1_integer_expression_storage_key = 'x'
            case (11_int32); mir_frontend_ast_v1_integer_expression_storage_key = ''
            case (12_int32); mir_frontend_ast_v1_integer_expression_storage_key = ''
            case (13_int32); mir_frontend_ast_v1_integer_expression_storage_key = 'x'
            case (14_int32); mir_frontend_ast_v1_integer_expression_storage_key = 'x'
            case (15_int32); mir_frontend_ast_v1_integer_expression_storage_key = ''
            case (16_int32); mir_frontend_ast_v1_integer_expression_storage_key = ''
            case (17_int32); mir_frontend_ast_v1_integer_expression_storage_key = 'x'
            case (18_int32); mir_frontend_ast_v1_integer_expression_storage_key = ''
            end select
        case (10_int32)
            select case (index)
            case (0_int32); mir_frontend_ast_v1_integer_expression_storage_key = ''
            case (1_int32); mir_frontend_ast_v1_integer_expression_storage_key = 'x'
            case (2_int32); mir_frontend_ast_v1_integer_expression_storage_key = 'x'
            case (3_int32); mir_frontend_ast_v1_integer_expression_storage_key = ''
            case (4_int32); mir_frontend_ast_v1_integer_expression_storage_key = ''
            case (5_int32); mir_frontend_ast_v1_integer_expression_storage_key = 'x'
            case (6_int32); mir_frontend_ast_v1_integer_expression_storage_key = ''
            end select
        end select
    end function mir_frontend_ast_v1_integer_expression_storage_key

end module ffc_mir_metadata
